"""empty message

Revision ID: 27b5dbd709e3
Revises: c165ac2b16d3
Create Date: 2022-12-06 17:25:13.740275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b5dbd709e3'
down_revision = 'c165ac2b16d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.drop_index('marca')
        batch_op.create_unique_constraint(None, ['modelo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('marca', ['marca'], unique=False)

    # ### end Alembic commands ###
